name: 30 days Code Challenge

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
jobs:
    check:
        name: Check code base
        runs-on: ubuntu-latest
        container:
            'image': node:20
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - run: echo "Checked Code"
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

